pipeline {
    agent any

    triggers {
        pollSCM('H/3 * * * *')
    }

    environment {
        DOCKER = credentials('docker-hub')
    }

    stages {

        stage('Prepare') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/CSID-DGU/2025-2-OSSPrac-sosprac-05.git',
                    credentialsId: 'github'
            }
        }

        stage('Build') {
            steps {
                sh 'docker compose build python-app'
            }
        }

        stage('Tag') {
            steps {
                script {
                    sh "docker tag sosprac_web ${DOCKER_USR}/sosprac_web:${BUILD_NUMBER}"
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    sh "echo $DOCKER_PSW | docker login -u $DOCKER_USR --password-stdin"
                    sh "docker push ${DOCKER_USR}/sosprac_web:${BUILD_NUMBER}"
                }
            }
        }
    }
}